
STD_LIB = ft_std.c
STD_SPLIT_STR = ft_split_str.c
DISPLAYING_LIB = displaying.c
INCLUDE = .

all:
	gcc -g -Wall -pedantic -O3 -o main $(DISPLAYING_LIB) horse_steps_v0.4.c $(STD_LIB) -I $(INCLUDE)

clean:
	rm *.o

fclean:
	rm -rf main


